
logging:
  config: classpath:log4j2.xml
  
---
 
spring:
  profiles: local
  application:
    name: Demo web app

server:
  port: 5002

# Actuator endpoint management
management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: shutdown,loggers,health,info,metrics
  endpoint:
    shutdown:
      enabled: true
      
app:
  requiredHttpHeaders: From,Authorization
  